const projects = [
  {
    Title: "Project 1",
    Url: "https://www.wwwwww.com",
    UrlRepo: "https://www.wwwwww.com",
    UrlImage: "https://www.wwwwww.com",
    Description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic,
    obcaecati eveniet.Nesciunt a modi,
    ex neque aliquid ratione ut velit sit doloremque,
    laudantium delectus temporibus, ad eum sed debitis exercitationem.`,
  },
  {
    Title: "Project 2",
    Url: "https://www.wwwwww.com",
    UrlRepo: "https://www.wwwwww.com",
    UrlImage: "https://www.wwwwww.com",
    Description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic,
    obcaecati eveniet.Nesciunt a modi,
    ex neque aliquid ratione ut velit sit doloremque,
    laudantium delectus temporibus, ad eum sed debitis exercitationem.`,
  },
  {
    Title: "Project 3",
    Url: "https://www.wwwwww.com",
    UrlRepo: "https://www.wwwwww.com",
    UrlImage: "https://www.wwwwww.com",
    Description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic,
    obcaecati eveniet.Nesciunt a modi,
    ex neque aliquid ratione ut velit sit doloremque,
    laudantium delectus temporibus, ad eum sed debitis exercitationem.`,
  },
  {
    Title: "Project 4",
    Url: "https://www.wwwwww.com",
    UrlRepo: "https://www.wwwwww.com",
    UrlImage: "https://www.wwwwww.com",
    Description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic,
    obcaecati eveniet.Nesciunt a modi,
    ex neque aliquid ratione ut velit sit doloremque,
    laudantium delectus temporibus, ad eum sed debitis exercitationem.`,
  },
  {
    Title: "Project 5",
    Url: "https://www.wwwwww.com",
    UrlRepo: "https://www.wwwwww.com",
    UrlImage: "https://www.wwwwww.com",
    Description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic,
    obcaecati eveniet.Nesciunt a modi,
    ex neque aliquid ratione ut velit sit doloremque,
    laudantium delectus temporibus, ad eum sed debitis exercitationem.`,
  },
];
